//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRISDBEntities : DbContext
    {
        public HRISDBEntities()
            : base("name=HRISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hrisPMSAppraisalDTL> hrisPMSAppraisalDTLs { get; set; }
        public virtual DbSet<hrisPMSAppraisalMST> hrisPMSAppraisalMSTs { get; set; }
        public virtual DbSet<hrisPMSAppraisalParam> hrisPMSAppraisalParams { get; set; }
        public virtual DbSet<V_hrisEMPLOYEE> V_hrisEMPLOYEE { get; set; }
    }
}
