//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrisPMSAppraisalDTL
    {
        public decimal PA_CTRL_NO { get; set; }
        public Nullable<int> SEQNO { get; set; }
        public string PANO { get; set; }
        public string TYPE { get; set; }
        public string KPI { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTION_PLAN { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> HIT_MISS { get; set; }
        public string FSCKPI { get; set; }
    
        public virtual hrisPMSAppraisalMST hrisPMSAppraisalMST { get; set; }
    }
}
