//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrisPMSAppraisalMST
    {
        public hrisPMSAppraisalMST()
        {
            this.hrisPMSAppraisalDTLs = new HashSet<hrisPMSAppraisalDTL>();
        }
    
        public string PANO { get; set; }
        public string EMPL_ID { get; set; }
        public string POSI_CODE { get; set; }
        public string EMPL_STATUS { get; set; }
        public string DEPT_CODE { get; set; }
        public string SEC_CODE { get; set; }
        public string EMPL_BRANCH { get; set; }
        public Nullable<System.DateTime> DATE_HIRED { get; set; }
        public Nullable<System.DateTime> EFF_DATE { get; set; }
        public string EMP_SBU { get; set; }
        public string HEAD_EMPL_ID { get; set; }
        public string HEAD_POSITION { get; set; }
        public string HEAD_DEPT { get; set; }
        public string HEAD_SEC { get; set; }
        public string HEAD_BRANCH { get; set; }
        public string HEAD_SBU { get; set; }
        public Nullable<System.DateTime> COVERED_FROM { get; set; }
        public Nullable<System.DateTime> COVERED_TO { get; set; }
        public Nullable<System.DateTime> DT_OF_AP { get; set; }
        public Nullable<System.DateTime> DT_OF_NX_AP { get; set; }
        public string COMMENTS { get; set; }
        public string RATED_BY { get; set; }
        public string VERIFIED_BY { get; set; }
        public string NOTED_BY_OPHEAD { get; set; }
        public string NOTED_BY_SBUHEAD { get; set; }
        public string ACKNOWLEDGEBY { get; set; }
        public Nullable<System.DateTime> ACKNOWLEDGEDATE { get; set; }
        public string ACKNOWLEDGEBYSUP { get; set; }
        public Nullable<System.DateTime> ACKNOWLEDGEDATESUP { get; set; }
        public string PAACKNOWLEDGEBY { get; set; }
        public Nullable<System.DateTime> PAACKNOWLEDGEDATE { get; set; }
        public string STATUS { get; set; }
        public string SOURCE { get; set; }
        public string CREA_BY { get; set; }
        public Nullable<System.DateTime> CREA_DT { get; set; }
        public string MODI_BY { get; set; }
        public Nullable<System.DateTime> MODI_DT { get; set; }
    
        public virtual ICollection<hrisPMSAppraisalDTL> hrisPMSAppraisalDTLs { get; set; }
    }
}
