//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrisPMSAppraisalParam
    {
        public decimal PARCTRNo { get; set; }
        public string PARPANO { get; set; }
        public string PARTYPE { get; set; }
        public string PARCODE { get; set; }
        public Nullable<decimal> PARWEIGHT { get; set; }
    }
}
