//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_mainkpi
    {
        public decimal KPIcode { get; set; }
        public string PANO { get; set; }
        public Nullable<decimal> KPITarget { get; set; }
        public string KPI_DESCRIPTION { get; set; }
        public string PAGROUP { get; set; }
        public int indicatorId { get; set; }
        public string crea_by { get; set; }
        public Nullable<System.DateTime> crea_date { get; set; }
    
        public virtual pms_indicators pms_indicators { get; set; }
    }
}
