//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_indicators
    {
        public pms_indicators()
        {
            this.pms_mainkpi = new HashSet<pms_mainkpi>();
            this.pms_subkpi = new HashSet<pms_subkpi>();
        }
    
        public int indicatorId { get; set; }
        public string description { get; set; }
        public decimal targetdef { get; set; }
        public string indicatortype { get; set; }
        public string positioncode { get; set; }
        public string positiondesc { get; set; }
        public string indicatorkra { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<pms_mainkpi> pms_mainkpi { get; set; }
        public virtual ICollection<pms_subkpi> pms_subkpi { get; set; }
    }
}
