//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_subkpiperformancerate
    {
        public string SUB_KPICODE { get; set; }
        public string EVENT_CODE { get; set; }
        public Nullable<decimal> ACTUAL_VALUE { get; set; }
        public Nullable<decimal> RESULT_VALUE { get; set; }
        public Nullable<System.DateTime> CREA_DATE { get; set; }
        public string CREA_BY { get; set; }
        public string WORKSTATION { get; set; }
        public Nullable<bool> ISPOSTED { get; set; }
        public Nullable<bool> ISPOSTED2 { get; set; }
        public string remarks { get; set; }
        public string KPITYPE { get; set; }
        public string RATEID { get; set; }
        public Nullable<int> ISREATED { get; set; }
    }
}
