//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_subkpi
    {
        public string SUBKPICODE { get; set; }
        public string PA_CTRL_NO { get; set; }
        public string SUBDESCRIPTION { get; set; }
        public Nullable<decimal> TARGET { get; set; }
        public string OCCURENCE { get; set; }
        public string HTMSIND { get; set; }
        public Nullable<decimal> HIT_PERCENTAGE { get; set; }
        public int ORDERBY { get; set; }
        public string EmpID { get; set; }
        public string AuthorityCde { get; set; }
        public string PaGroup { get; set; }
        public string pano { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isackhead { get; set; }
        public Nullable<bool> isacksub { get; set; }
        public int indicatorId { get; set; }
        public System.DateTime createdate { get; set; }
    
        public virtual pms_indicators pms_indicators { get; set; }
    }
}
