//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_hrisEMPLOYEE
    {
        public string EMPL_ID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeName2 { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string MNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string STATUS { get; set; }
        public string STATUSNAME { get; set; }
        public string STATUSNAMEEXT { get; set; }
        public string RELIGION { get; set; }
        public string SEX { get; set; }
        public string CIVILSTATUS { get; set; }
        public string CIVILSTATUSDESC { get; set; }
        public string BLOODTYPE { get; set; }
        public string EMAILADD { get; set; }
        public Nullable<System.DateTime> DATEHIRED { get; set; }
        public System.DateTime EFFECTIVITYDATE { get; set; }
        public Nullable<decimal> MONTHS { get; set; }
        public Nullable<decimal> DAYS { get; set; }
        public string CORPORATE { get; set; }
        public string CorporateName { get; set; }
        public string BRANCH { get; set; }
        public string BRANCHNAME { get; set; }
        public string BRANCHAREA { get; set; }
        public string POSITION { get; set; }
        public string POSITIONNAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string SECTION { get; set; }
        public string SECTIONNAME { get; set; }
        public string LEVELCODE { get; set; }
        public string LEVELNAME { get; set; }
        public string JobLevelGroup { get; set; }
        public string CLASS { get; set; }
        public string TYPE { get; set; }
        public string TYPEDESCRIPTION { get; set; }
        public string RATECLASS { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> ECOLA { get; set; }
        public string TIN { get; set; }
        public string SSS { get; set; }
        public string GSIS { get; set; }
        public string HDMF { get; set; }
        public string PHILHEALTH { get; set; }
        public string WTAXSTATUS { get; set; }
        public string EmployeePresentAddress { get; set; }
        public string EmployeeHomeAddress { get; set; }
        public string EmployeePresentContactNO { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string SHOESSIZE { get; set; }
        public string SHIRTSIZE { get; set; }
        public string HAIRCOLOR { get; set; }
        public string EYECOLOR { get; set; }
        public string DISTMARK { get; set; }
        public string CITIZENSHIP { get; set; }
        public Nullable<System.DateTime> MARRIAGEDATE { get; set; }
        public string HOME_CONTACT { get; set; }
        public string EMER_NAME { get; set; }
        public string EMER_ADDRESS { get; set; }
        public string EMER_RELATION { get; set; }
        public string EMER_CONTACT { get; set; }
        public string AGENCYCODE { get; set; }
        public string AGENCYNAME { get; set; }
        public string SEPARATIONTYPE { get; set; }
        public string SEPARATIONTDESC { get; set; }
        public Nullable<System.DateTime> LASTPICUPDATED { get; set; }
        public string ImmediateID { get; set; }
        public string ImmediateName { get; set; }
        public Nullable<System.DateTime> ImmediateBDay { get; set; }
        public string ImmediateStatus { get; set; }
        public string ImmediateEmail { get; set; }
        public Nullable<System.DateTime> ImmediateDHired { get; set; }
        public string ImmediateSBU { get; set; }
        public string ImmediateBranch { get; set; }
        public string ImmediatePosition { get; set; }
        public string ImmediateDepartment { get; set; }
        public string ImmediateSection { get; set; }
        public string ImmediateLevel { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public string PicturePath { get; set; }
        public string EMPL_RELIGION { get; set; }
        public Nullable<System.DateTime> SEPARATED_DATE { get; set; }
        public string EMAILNOTIFICATION { get; set; }
        public Nullable<byte> Is_BLACKLISTED { get; set; }
        public Nullable<System.DateTime> CONTRACTENDDATE { get; set; }
        public Nullable<decimal> SEA { get; set; }
        public Nullable<byte> EXITINTERVIEW { get; set; }
        public Nullable<byte> ISDESIRED { get; set; }
        public string DESIREDREMARKS { get; set; }
        public string PAYROLL_TYPE { get; set; }
    }
}
